APPLICATION = iot_app
BOARD ?= native
RIOTBASE ?= $(CURDIR)/RIOT

USEMODULE += gps
USEMODULE += _can

EXTERNAL_MODULE_DIRS += $(CURDIR)

DEVELHELP ?= 1
QUIET ?= 1

include $(RIOTBASE)/Makefile.include
